# Consume a release supplied by SovKit. Never build or rewrite SDK artifacts.
set(devtools_default_sdk "${CMAKE_CURRENT_SOURCE_DIR}/3rdparty/sovkit_sdk/0.1.0")
set(SOVKIT_SDK_ROOT "${devtools_default_sdk}" CACHE PATH "SovKit-supplied SDK package")
# Migrate the old built-in staging location, including existing VS solutions.
cmake_path(ABSOLUTE_PATH SOVKIT_SDK_ROOT NORMALIZE OUTPUT_VARIABLE devtools_selected_sdk)
if("${SOVKIT_SDK_ROOT}" STREQUAL "" OR
   devtools_selected_sdk STREQUAL "${CMAKE_CURRENT_SOURCE_DIR}/.sdk/windows-x64-current")
  message(STATUS "Switching the legacy SDK staging path to ${devtools_default_sdk}")
  set(SOVKIT_SDK_ROOT "${devtools_default_sdk}" CACHE PATH "SovKit-supplied SDK package" FORCE)
endif()

# Accept the supplied flat package and SovKit's documented include/lib layout.
if(EXISTS "${SOVKIT_SDK_ROOT}/sovkit.h")
  set(SOVKIT_SDK_INCLUDE_DIR "${SOVKIT_SDK_ROOT}")
else()
  set(SOVKIT_SDK_INCLUDE_DIR "${SOVKIT_SDK_ROOT}/include")
endif()
set(SOVKIT_SDK_HEADER "${SOVKIT_SDK_INCLUDE_DIR}/sovkit.h")
if(NOT EXISTS "${SOVKIT_SDK_HEADER}")
  message(FATAL_ERROR "Missing SovKit-supplied sovkit.h in ${SOVKIT_SDK_ROOT}. Select a complete package with -DSOVKIT_SDK_ROOT=...")
endif()

if(WIN32)
  set(SOVKIT_RUNTIME_NAME libsovkit.dll)
elseif(APPLE)
  set(SOVKIT_RUNTIME_NAME libsovkit.dylib)
else()
  set(SOVKIT_RUNTIME_NAME libsovkit.so)
endif()
set(SOVKIT_RUNTIME "${SOVKIT_SDK_ROOT}/${SOVKIT_RUNTIME_NAME}")
foreach(subdir lib bin)
  if(NOT EXISTS "${SOVKIT_RUNTIME}" AND EXISTS "${SOVKIT_SDK_ROOT}/${subdir}/${SOVKIT_RUNTIME_NAME}")
    set(SOVKIT_RUNTIME "${SOVKIT_SDK_ROOT}/${subdir}/${SOVKIT_RUNTIME_NAME}")
  endif()
endforeach()
if(NOT EXISTS "${SOVKIT_RUNTIME}")
  message(FATAL_ERROR "Missing ${SOVKIT_RUNTIME_NAME} in ${SOVKIT_SDK_ROOT}. Obtain the target-platform library from SovKit; DevTools does not build the SDK.")
endif()

set(SOVKIT_SDK_DOCUMENTATION "${SOVKIT_SDK_ROOT}/SDK_INTEGRATION.md")
if(NOT EXISTS "${SOVKIT_SDK_DOCUMENTATION}")
  set(SOVKIT_SDK_DOCUMENTATION "${SOVKIT_SDK_ROOT}/README.md")
endif()
if(NOT EXISTS "${SOVKIT_SDK_DOCUMENTATION}")
  message(FATAL_ERROR "Missing SovKit integration documentation in ${SOVKIT_SDK_ROOT}")
endif()
message(STATUS "SovKit SDK (supplied package): ${SOVKIT_SDK_ROOT}")
message(STATUS "SovKit runtime: ${SOVKIT_RUNTIME}")
